# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  windows-build:
    runs-on: windows-latest

    strategy:
      matrix:
        vs:
          version:
            - 2017
            - 2019
          config:
            - Debug
            - Profile
            - Release
          platform:
            - x64
        gmake:
          config:
            - debug
            - profile
            - release
          platform:
            - 64

    steps:
      - uses: actions/checkout@v2

      - name: orx setup
        run: ./setup.bat

      - name: orx build (gmake)
        working-directory: code/build/windows/gmake
        run: make config=${{ matrix.gmake.config }}${{ matrix.gmake.platform }}

      - uses: microsoft/setup-msbuild@v1.1

      - name: orx build (msbuild)
        run: msbuild code/build/windows/vs${{ matrix.vs.version }}/orx.sln /p:Platform=${{ matrix.vs.platform }} /p:Configuration=${{ matrix.vs.config }}
